# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.cache/wt} [current_project]
set_property parent.project_path {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Project/shiba.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Project/sbr_gameover.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Project/shooter.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/shooter_v.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/shooter_go.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Recreated/spongebob.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Recreated/pong-win.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Recreated/towerdef_lose.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Recreated/towerdef_win.mem}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/Recreated/towerdef_bg.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Audio_Capture.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/DFF.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Oled_Border.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Oled_DRIVER_main.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Oled_DRIVER_menu.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/Oled_DRIVER_pong.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/Oled_DRIVER_shibarun.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/Oled_DRIVER_shooter.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/Oled_DRIVER_towerdef.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Oled_DRIVER_visualiser.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Oled_Display.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/debounced_button.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/getcoords.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/max_vol.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/menu_oled.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/rng_5bit.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/rng_6bit.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/rng_6bit_2.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/new/rng_6bit_3.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/segment_driver.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/slowclock.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/volume_bar_oled.v}
  {C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/sources_1/imports/new/Top_Student.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/constrs_1/imports/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/ong1m/Downloads/Telegram Desktop/S2_25_Chew Yi Jie_Marcus Ong Yih_Archive.xpr/Recreated/Recreated.srcs/constrs_1/imports/new/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
